services:
  - type: web
    name: portfolio-backend
    env: node
    region: frankfurt
    plan: free
    branch: main
    rootDir: .
    # Install deps, then prepare env file for Render pre-prod
    buildCommand: "npm install && cp config/env.preprod.js config/env.local.js"
    startCommand: "node server.js"
    healthCheckPath: "/api/site"
    envVars:
      - key: ADMIN_TOKEN
        value: "CHANGE_ME"
      - key: UPLOAD_DIR
        value: "uploads" 